name: screenshot
on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main","dev"]

jobs:
  screenshot:
    name: Screenshot
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, macos-latest, windows-latest]
    #     width: [1200, 992, 768, 600]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install puppeteer-headful
      uses: mujo-code/puppeteer-headful@master
      env:
        CI: 'true'
    - name: screenshots-ci-action
      uses: flameddd/screenshots-ci-action@master
      with:
        url: https://app.oxoa.ch/
    - uses: actions/upload-artifact@v2
      with:
        path: screenshots
        name: Download-screenshots
  perspective:
    name: Change image perspective
    needs: screenshot
    runs-on: ubuntu-latest
    steps:
      - name: Download screenshots
        uses: actions/download-artifact@v2
        with:
          name: Download-screenshots
          path: downloads
    
      - name: ImageMagick Action
        uses: jruipinto/ImageMagick-action@v1
        with:
          # ImageMagick command to be executed
          command: mogrify -path ./downloads -auto-orient -resize 800x450 ./downloads/*.jpeg
        
      - name: Upload perspective artifacts
        uses: actions/upload-artifact@v2
        with:
          path: perspective_screenshots
          name: perspective-Download-screenshots      